# =============================================================================
# EXERCISE 5: Secrets and Permissions (BROKEN)
# =============================================================================
# This deployment workflow works for maintainers but fails for fork PRs.
# It also has permission issues when pushing to the container registry.
#
# SCENARIO:
# - Maintainer pushes to main: Works perfectly
# - Fork PR is opened: Fails with "secret not found"
# - Push to GHCR: Sometimes fails with "403 Forbidden"
#
# Your task: Fix the workflow to handle fork PRs securely and fix permissions.
#
# HINTS:
# - Understand how secrets work differently for fork PRs
# - Check the permissions block
# - Consider what permissions GITHUB_TOKEN needs
# - Think about which steps should run for forks vs internal PRs
#
# There are 4 issues to fix in this workflow.
# =============================================================================

name: Exercise 5 - Secrets and Permissions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# ISSUE 1: Missing or incorrect permissions block
# The workflow needs specific permissions but they're not declared
permissions:
  contents: read
  packages: write     # Needed to push to GHCR
  pull-requests: read # Needed to read PR info (optional)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build application
        run: |
          echo "Building..."
          mkdir -p dist
          echo "Build complete" > dist/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/

  # ISSUE 2: This job tries to use secrets that aren't available from forks
  deploy-preview:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      # This step uses a secret that won't exist for fork PRs
      - name: Deploy preview
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          if [ -z "$DEPLOY_TOKEN" ]; then
            echo "Error: DEPLOY_TOKEN not set"
            exit 1
          fi
          echo "Deploying preview with token..."

  # ISSUE 3: This job needs packages:write permission for GHCR
  push-to-registry:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      # ISSUE 4: Login step uses wrong authentication approach
      - name: Login to GHCR
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest
