# =============================================================================
# EXERCISE 6: Matrix Include/Exclude (BROKEN)
# =============================================================================
# This workflow tests across multiple OS and Node.js versions.
# The team wants to:
#   1. Skip ALL Windows jobs (too slow in CI)
#   2. Add an "experimental" flag only to Node 22 jobs
#   3. Skip the Ubuntu + Node 18 combination (known issues)
#
# But the matrix configuration isn't working as expected:
#   - Windows jobs are still running
#   - The experimental flag isn't being applied correctly
#   - Some exclude entries aren't having any effect
#
# Your task: Fix the matrix configuration to achieve the desired behavior.
#
# HINTS:
# - Read the docs on how exclude matches combinations
# - Check if include entries have all required properties
# - Think about what "exact match" means for exclude
#
# There are 4 issues to fix in this workflow.
# =============================================================================

name: Exercise 6 - Matrix Include/Exclude

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20, 22]

        # ISSUE 1: This exclude is supposed to skip ALL Windows jobs
        # but Windows jobs are still running
        exclude:
          - os: windows-latest

        # ISSUE 2: This exclude should skip Ubuntu + Node 18
        # but it's not working
        exclude:
          - os: ubuntu-latest
            node: "18"

        # ISSUE 3: This include should add experimental: true to Node 22 jobs
        # but the flag isn't being applied
        include:
          - node: 22
            experimental: true

    # ISSUE 4: This references matrix.experimental but it might be undefined
    # for some combinations, causing unexpected behavior
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Show matrix info
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Node: ${{ matrix.node }}"
          echo "Experimental: ${{ matrix.experimental }}"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
