# =============================================================================
# EXERCISE 5: Secrets and Permissions (SOLUTION)
# =============================================================================
# This is the corrected version with all issues fixed.
# =============================================================================

name: Exercise 5 - Secrets and Permissions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# FIX 1: Add explicit permissions block
# Without explicit permissions, workflows get default permissions which
# may or may not include what you need (depending on repo settings).
#
# BEST PRACTICE: Always declare minimal permissions explicitly.
# This follows the principle of least privilege and makes the workflow
# more secure and self-documenting.
permissions:
  contents: read      # Needed to checkout code
  packages: write     # Needed to push to GHCR
  pull-requests: read # Needed to read PR info (optional)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build application
        run: |
          echo "Building..."
          mkdir -p dist
          echo "Build complete" > dist/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/

  # FIX 2: Handle fork PRs properly
  # Secrets are NOT available for workflows triggered by fork PRs.
  # This is a security feature - you don't want forks to access your secrets!
  #
  # Solutions:
  # A) Skip steps that need secrets for fork PRs
  # B) Use pull_request_target (DANGEROUS - runs with repo permissions)
  # C) Use a two-workflow approach (build in PR, deploy on comment)
  #
  # Here we use option A: conditional execution
  deploy-preview:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      # Check if this is a fork PR
      - name: Check if fork
        id: fork-check
        run: |
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "is_fork=true" >> $GITHUB_OUTPUT
            echo "This is a fork PR - secrets not available"
          else
            echo "is_fork=false" >> $GITHUB_OUTPUT
            echo "This is an internal PR - secrets available"
          fi

      # Only run deployment for internal PRs (not forks)
      - name: Deploy preview
        if: steps.fork-check.outputs.is_fork != 'true'
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          if [ -z "$DEPLOY_TOKEN" ]; then
            echo "Error: DEPLOY_TOKEN not set"
            exit 1
          fi
          echo "Deploying preview with token..."

      # For fork PRs, show a helpful message instead of failing
      - name: Fork PR notice
        if: steps.fork-check.outputs.is_fork == 'true'
        run: |
          echo "::notice::Preview deployment skipped for fork PRs (secrets not available)"
          echo "The build was successful. A maintainer will review and may deploy a preview."

  # FIX 3 & 4: Use GITHUB_TOKEN for GHCR authentication
  # The original code used a PERSONAL_ACCESS_TOKEN, which:
  # - Requires manual creation and rotation
  # - Could be a security risk if leaked
  # - Isn't necessary for pushing to same repo's GHCR
  #
  # GITHUB_TOKEN is automatically provided and scoped correctly.
  # Just need to ensure permissions.packages: write is set (Fix 1).
  push-to-registry:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # You can also set job-level permissions if needed
    # (but we already set workflow-level permissions)
    # permissions:
    #   packages: write
    #   contents: read

    steps:
      - uses: actions/checkout@v4

      # FIX 4: Use GITHUB_TOKEN instead of personal access token
      # secrets.GITHUB_TOKEN is automatically available in all workflows.
      # It's scoped to the current repository and expires after the workflow.
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Alternative: Use the docker/login-action (recommended)
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest

# =============================================================================
# SUMMARY OF FIXES:
# =============================================================================
#
# 1. Added explicit permissions block
#    - contents: read    - Checkout code
#    - packages: write   - Push to GHCR
#    - Principle of least privilege
#
# 2. Handle fork PRs gracefully
#    - Check if PR is from a fork
#    - Skip secret-dependent steps for forks
#    - Show helpful notice instead of failing
#
# 3. Use workflow-level permissions for GHCR
#    - packages: write enables GHCR push
#
# 4. Use GITHUB_TOKEN instead of PAT
#    - Automatic, no manual management
#    - Properly scoped to repository
#    - More secure than long-lived PATs
#
# SECURITY CONCEPTS:
#
# Fork PR Security Model:
# - Forks don't get access to secrets
# - Forks run with read-only permissions
# - This prevents malicious PRs from:
#   - Stealing secrets
#   - Pushing to registries
#   - Modifying repository
#
# pull_request_target (DANGEROUS):
# - Runs in context of BASE repo, not fork
# - HAS access to secrets
# - Only use if you REALLY understand the risks
# - Never checkout and run code from the PR directly
#
# GITHUB_TOKEN Permissions:
# - Can be scoped per-workflow or per-job
# - Defaults can be set in repo settings
# - Always declare explicitly for clarity
#
# Available Permissions:
#   actions: read/write         - Workflow runs
#   checks: read/write          - Check runs/suites
#   contents: read/write        - Repository contents
#   deployments: read/write     - Deployments
#   id-token: write             - OIDC tokens
#   issues: read/write          - Issues
#   packages: read/write        - Packages/GHCR
#   pages: read/write           - GitHub Pages
#   pull-requests: read/write   - Pull requests
#   repository-projects: read/write - Projects
#   security-events: read/write - Code scanning
#   statuses: read/write        - Commit statuses
# =============================================================================
